### PR TITLE
Restructure docs

### PR DESCRIPTION
**Pull request by thet**
- Factor all DocTestSuites out to DocFileSuites and include them in the /docs/index file.
- Apply documentation styleguide.

### CODE REVIEW

**Comment by thet** [comment]
@svx @jensens

**Comment by thet** [comment]
@svx @jensens 
i've had a talk with @svx about the location of documentation and the role of doctests as documentation. basically i agree, that many doctests shouldn't be included in documentation, but not in this case. IMO with doctests in plone.memoize contain interesting and important information for developers. see:
https://github.com/plone/plone.memoize/blob/thet-restructure-docs/plone/memoize/volatile.rst
https://github.com/plone/plone.memoize/blob/thet-restructure-docs/plone/memoize/view.rst

still, these are the core tests for this package and i don't feel like i want them to live in the /docs folder of the package. but the @plone/documentation-team position is that all documentation should be in the /docs folder. therefore, referencing them from an /docs/index.rst file is wrong.

should we move all documentation-worth doctests to /docs and let the test suite initialization code reference them from there or should the @plone/documentation-team policy be modified to allow /docs/index.rst reference doctests from the package source directory? in the latter case, we'd need https://github.com/plone/papyrus/pull/89

**Comment by gforcada** [comment]
FYI plone.api gas something like that: it symlinks on tests folder the
doctests found in docs folder.

Is that best practices?
El dia 21/12/2015 0:02, "Johannes Raggam" <notifications@github.com> va
escriure:

**Comment by jensens** [comment]
@thet - having doctests as additional information has sometimes some value. But at the moment its the only documentation and thats really really bad. 

I always see doctests as a method to write verbose tests, explaining what happens to the reader of the tests, audience is here a person who need to touch the code of plone.memoize itself. 

I dont see doctests as documentation for the user of plone.memoize. That mainly because the nature of a test is to be very verbose, including all edge cases and so having a low signal noise ratio. 

Opposed to many in Plone community I like doctests for some cases. But I think the "doc" in it was badly choosen in its name.

**Comment by thet** [comment]
I do disagree, partly. Especially doctests often test the API of a package and thus show the user - who is a developer - how to use the API. I agree, tests also have to cover edge cases, which are of little value for everyday use.

Ideally documentation with code examples should be written in a way, that they can be tested. And also should be included in the test setup. This ensures, that the docs stay up to date with code changes.

IMO, if we want someone to read the tests like documentation, doctests are ideal. For unit tests or testing edge cases, plain python test files are much better.

**Comment by thet** [comment]
I think the only controversial thing with merging this is the docs/index.rst - because that would imply that doctests can be referenced in docs/index.rst. True?

**Comment by jensens** [comment]
however, this PR can be merged, including it is a papyrus thing i suppose

**Pull request merged**
