### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/812/

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/815/

**Comment by thet** [comment]
tnx for the Py3 effort!
can we have a tox.ini and .travis config, so that we can test all supported python versions at once, local and on travis? example see: https://github.com/collective/icalendar/

**Comment by tomgross** [comment]
I can add a travis config but I can't activate it in the plone repo

**Comment by thet** [comment]
I can do that

**Comment by jensens** [comment]
i enabled it, please check if all works

**Comment by tomgross** [comment]
All green now https://travis-ci.org/plone/plone.memoize

**Comment by thet** [comment]
I re-started jenkins: http://jenkins.plone.org/job/pull-request-5.0/851/
I'm expecting this going to be green.
A nice thing would be to squash the commits... /cc @tomgross

**Comment by thet** [comment]
@tomgross for me the last Jenkins Failure seems unrelated. Also, it's different from previous runs.
Do you have an idea?
Trying again: http://jenkins.plone.org/job/pull-request-5.0/854/

**Comment by jensens** [comment]
this is kind of strange, maybe some test isolation issue?

btw., i'd not squash commits, this way its easy to get what was changed and why.

**Comment by thet** [comment]
HA! It's green! quick! merging before anything breaks again! ;)

**Pull request merged**
